# Permalinks
permalink:           pretty

# Setup
title:               DeepIntent
tagline:             Learning to Model Pedestrian Intent in Autonomous Driving Scenarios
url:                 http://autonomylab.org
paginate:            1
baseurl:             /deep_intent

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Pratik Gujjar
  url:               http://autonomylab.org
  email:             pgujjar@sfu.ca

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/AutonomyLab/deep_intent

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
